name: frontend_test_deploy

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

  workflow_dispatch:

jobs:
  Build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 18
          
      - name: Install Dependencies
        working-directory: ./frontend
        run: npm ci
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/autoavenue-frontend:latest
